---
    - name: Check disk space
      hosts: all
      become: true
      
      tasks:
        - name: display HOME
          ansible.builtin.debug:
            msg: "{{ lookup('env', 'HOME') }}"
          
        - name: Get disk usage
          command: df -h
          register: disk_usage

        - name: Check disk space available
          shell: df -h / | awk 'NR==2 {print $5}'
          register: disk_usage
                
        - name: Send a message to the Discord channel
          community.general.discord:
            # https://discord.com/api/webhooks/nnnnnnnnnn/xxxxxxxxxxxxxxxxxxxxxxxxxxx
            #                                  |        | |                         |
            #                  webhook_id <----'--------' |                         |
            #                                             |                         |
            #                  webhook_token <------------'-------------------------'
            webhook_id: $DISCORD_ID_ANSIBLE
            webhook_token: $DISCORD_TOKEN_ANSIBLE
            content: "Current disk usage on ***{{ inventory_hostname }}***  :  {{ disk_usage.stdout[:-1]|int }}%"
