---
- name: Check disk space
  hosts: all
  gather_facts: true
  become: true

  vars:
    playbook_name: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split()|select('match','^[a-z-_/]*[.]y[a]*ml')|list|first|basename }}"
      
  tasks:
    - set_fact:
          down: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
    - name: send notification if any host is unreachable
      community.general.discord:
        webhook_id: "{{ discord_id_ansible }}"
        webhook_token: "{{ discord_token_ansible }}"
        content: "<@&1294264865011273800>"
        embeds:
          - title: "Host Unreachable"
            description: | 
                        List : 
                        --------------------------------------------
                        {% for item in down -%}                                               
                        **{{ item }}**                                                           
                        {% endfor %}
                        --------------------------------------------
            footer:
              text: "Script : {{ playbook_name }}"
      when: down
      run_once: true
    - name: Get disk usage
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage
    - block:
      - name: wait in serial
        command: sleep 1
      - name: Send a message to the Discord channel
        community.general.discord:
        # https://discord.com/api/webhooks/nnnnnnnnnn/xxxxxxxxxxxxxxxxxxxxxxxxxxx
        #                                  |        | |                         |
        #                  webhook_id <----'--------' |                         |
        #                                             |                         |
        #                  webhook_token <------------'-------------------------'
          webhook_id: "{{ discord_id_ansible }}"
          webhook_token: "{{ discord_token_ansible }}"
          content: "Current disk usage on ***{{ inventory_hostname }}***  :  {{ disk_usage.stdout[:-1]|int }}%"
      when: disk_usage.stdout[:-1]|int > 1
