---
- hosts: all
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: full
      become: true
      tags: apt
    - name: Install ntpdate
      ansible.builtin.package:
        name: ntpdate
        state: present
      become: true
    - name: Print OS info
      ansible.builtin.package:
        name: apache2
        state: present
      become: true
