- hosts: all
  gather_facts: true
  #ignore_unreachable: true
  #ignore_errors: true
  vars:
    playbook_absoluteName: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split() | select('match','^.*[.]ya?ml$') | list | first }}"
    playbook_baseName: "{{ playbook_absoluteName | basename }}"
  tasks:
    - debug:
        var: item
      loop:
        - "{{ playbook_absoluteName }}"
        - "{{ playbook_baseName }}"
    - block:
      - set_fact:
          down: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
      - name: send notification if any host is unreachable
        community.general.discord:
          webhook_id: "{{ discord_id_ansible }}"
          webhook_token: "{{ discord_token_ansible }}"
          content: "<@&1294264865011273800>"
          embeds:
            - title: "Error - Unreachable"
              description: | 
                          The following hosts are unreachable : 
                          
                          **`{{ down }}`**
                          
              footer:
                text: "Script : test.yml"
        when: down
      run_once: true
    - block:
      - name: Install Network Tools
        ignore_errors: true
        become: true
        apt:
          pkg:
            - net-tools
            - dnsutils
            - software-properties-common
            - tcpdump
            - cifs-utils
            - curl
            - traceroute
            - 1991dnsutils1991
          state: present
          update_cache: yes
        register: result
      - name: send notification if failed
        community.general.discord:
          webhook_id: "{{ discord_id_ansible }}"
          webhook_token: "{{ discord_token_ansible }}"
          content: "<@&1294264865011273800>"
          embeds:
            - title: "Task Failed"
              description: |
                          The task for the following host failed : **`{{ inventory_hostname }}`**

                          Recap : `{{ result }}`
                          
              footer:
                text: "Script : test.yml"
        when: result.failed == True
