- hosts: all
  #ignore_unreachable: true
  ignore_errors: true
  tasks:
    
    - name: Install Network Tools
      become: true
      apt:
        pkg:
          - net-tools
          - dnsutils
          - software-properties-common
          - tcpdump
          - cifs-utils
          - curl
          - traceroute
        state: present
        update_cache: yes
      register: result
      notify:
        - notify failed
    - meta: flush_handlers
        
  handlers:
      - name: notify failed
        community.general.discord:
          webhook_id: "{{ discord_id_ansible }}"
          webhook_token: "{{ discord_token_ansible }}"
          content: "<@&1294264865011273800>"
          embeds:
            - title: "Test Script"
              description: '**Ansible message from `{{ inventory_hostname }}`**: {{ result }}'
              footer:
                text: "Script : test.yml"
      #when : "'FAILED' in result.stderr"
      
