---
- hosts: all
  become: true
  tasks:
    # Upgrade packages
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
      state: latest
        
    # Install network tools
    - name: Install network tools
      ansible.builtin.apt:
        pkg:
          - net-tools
          - dnsutils
          - software-properties-common
      state: present
      update_cache: yes
