---
- hosts: all
  become: true
  tasks:
    # Upgrade packages
    - name: Upgrade packages
      apt:
        upgrade: yes
        update_cache: yes
        
    # Install network tools
    - name: Install network tools
      apt:
        pkg:
          - net-tools
          - dnsutils
          - software-properties-common
      state: present
      update_cache: yes
