- hosts: all

  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Send a embedded message to the Discord channel
      community.general.discord:
        webhook_id: "{{ discord_id_ansible }}"
        webhook_token: "{{ discord_token_ansible }}"
        content: "<@&1294264865011273800>"
        embeds:
          - title: "Packages update"
            description: "Reboot is required on : ***{{ inventory_hostname }}***"
            footer:
              text: "Script : update-aptpackages.yml"
      when : reboot_required.stat.exists
