---
- hosts: all
  become: true
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
      state: latest
