---
    - name: Update and upgrade apt packages
      hosts: all
      become: true
      
      tasks:
        - name: Update packages with apt
          when: ansible_pkg_mgr == 'apt'
          ansible.builtin.apt:
            update_cache: true
    
#        - name: Update packages with yum
#          when: ansible_pkg_mgr == 'yum'
#          ansible.builtin.yum:
#            name: '*'
#            state: latest # noqa: package-latest
    
        - name: Upgrade packages with apt
          when: ansible_pkg_mgr == 'apt'
          ansible.builtin.apt:
            upgrade: dist
    
#        - name: Upgrade packages with yum
#          when: ansible_pkg_mgr == 'yum'
#          ansible.builtin.yum:
#            name: '*'
#            state: latest # noqa: package-latest
#            exclude: kernel*

        # Check if reboot is required
        - name: check if system reboot is required
          stat:
            path: /var/run/reboot-required
          register: reboot_required
    
        - name: Send a embedded message to the Discord channel
          community.general.discord:
            # https://discord.com/api/webhooks/nnnnnnnnnn/xxxxxxxxxxxxxxxxxxxxxxxxxxx
            #                                  |        | |                         |
            #                  webhook_id <----'--------' |                         |
            #                                             |                         |
            #                  webhook_token <------------'-------------------------'
            webhook_id: "{{ discord_id_ansible }}"
            webhook_token: "{{ discord_token_ansible }}"
            content: "<@&1294264865011273800>" # Tagged Role : @Pings
            embeds:
              - title: "Packages update"
                description: "Reboot is required on : ***{{ inventory_hostname }}***"
                footer:
                  text: "Script : update-apt.yml"
          when : reboot_required.stat.exists
