- hosts: "{{ my_hosts | d([]) }}"
#- hosts: all

  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify discord
      vars:
      notify_discord_username: Ansible
    # https://discord.com/api/webhooks/nnnnnnnnnn/xxxxxxxxxxxxxxxxxxxxxxxxxxx
    #   notify_discord_webhook_id <----'--------' |                         |
    #   notify_discord_webhook_token <------------'-------------------------'
      notify_discord_webhook_id: '1294000184828891276'
      notify_discord_webhook_token: 'Nad1Tc5wbTY2jpI3u9xfrJ-LZnn4rBZnCtpjzDihYqtKt9MtVdApgvzuN_kLUXRmG1_f'
      notify_discord_webhook_id_regex: '^0|[1-9][0-9]*$'
      notify_discord_webhook_token_regex: '^[a-zA-Z0-9_-]+$'
      notify_discord_webhook_content: "Reboot required on {{ inventory_hostname }}"
      notify_discord_send_from_host: localhost

    - name: Send Discord message
      community.general.discord:
        username: "{{ notify_discord_username }}"
        webhook_id: "{{ notify_discord_webhook_id }}"
        webhook_token: "{{ notify_discord_webhook_token }}"
        content: "{{ notify_discord_webhook_content }}"
      delegate_to: "{{ notify_discord_send_from_host }}"
      when:
        - notify_discord_webhook_id is match(notify_discord_webhook_id_regex)
        - notify_discord_webhook_token is match(notify_discord_webhook_token_regex)
        - notify_discord_webhook_content | length > 0
        - notify_discord_send_from_host is in (['localhost'] + groups['all'])
        - reboot_required.stat.exists
